title: Ground Floor
email: manbeejay@outlook.com
description: >- 
  The Winding Staircase
baseurl: "" # The subpath of your site, e.g., /blog
url: "https://manbeejay.github.io" # The base hostname
theme: jekyll-theme-cayman
